- job_name: 'ec2'
  metrics_path: /metrics
  static_configs:
    - targets: 
      - 3.145.173.16:9100
      - 3.145.173.16:80
      - 3.15.12.63:9100
      - 3.15.12.63:80
- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://3.145.173.16
      - http://3.15.12.63
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring:9115